[project]
name = "panhumanpy"
version = "0.1.0"
description = "A Python package for automated cell type annotation using neural networks"
channels = ["conda-forge"]
platforms = ["linux-64"]

# Runtime dependencies - necessary for the package to function
[dependencies]
python = "==3.12.8"
pip = "*"
numpy = "==1.26.4"
pandas = "==2.2.3"
scikit-learn = "==1.6.0"
h5py = "==3.12.1"
anndata = "==0.10.9"
python-dateutil = "*"
umap-learn = "==0.5.7"
numba = "==0.60.0"
pytest = "8.3.*"



# PyPI dependencies - installed via pip
[pypi-dependencies]
panhumanpy = { path = ".", editable = true }
hatchling = ">=1.18.0"
# hatch-tensorflow-detector = ">=0.1.0"

# Tasks for development workflows
[tasks]
test = "pytest tests/"
lint = "pre-commit run --all-files"
format = { cmd = "black src/ tests/", depends-on = [] }
check = { depends-on = ["test", "lint"] }
build = "python -m build"
docs = "mkdocs serve"

# TensorFlow installation options
tf-cpu = "pip install tensorflow-cpu==2.17.0 keras==3.7.0"
tf-gpu = "pip install tensorflow[and-cuda]==2.17.0 keras==3.7.0"