[project]
name = "panhumanpy-test"
version = "0.1.0"
description = "Test environment"
channels = ["conda-forge"]
platforms = ["linux-64"]

[dependencies]
python = "3.12.8"
pip = "*"

[tasks]
test = "python -c 'print(\"Test successful!\")'"